name = "wxc-oidc"
main = "dist/main.mjs"
compatibility_date = "2024-11-01"

# Custom domain configuration
# Note: Custom domains are managed via Cloudflare Workers dashboard
# The oidc.nyworking.us domain is configured there

#zone_id = "your-zone-id"  # Not needed when using custom domains

[durable_objects]
bindings = [
  { name = "DO_OIDC", class_name = "OpenIDConnectDurableObject" },
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["OpenIDConnectDurableObject"]

[build]
command = "npm run build"
cwd = "."
watch_dir = ["src"]
